### ISSUE TITLE
[获取SessionlD] data解码:'bind': False

### ISSUE THREAD

**Issue by sssolitude** [ChrisKimZHT/WHUT-AutoHealthReport#1]
[获取SessionlD]返回消息:
'status ': True, 'code': o, 'message': None, 'data':
'' , 'otherData': 0}
[获取SessionlD] data解码:
{'bind": False, 'sessionld': ''}[绑定身份]返回消息:
{'status': False, 'code': 50000, 'message':'身份证信息错误', 'data': None, "otherData': {}
[解绑账号]返回消息:
{'status': True,'code': o, 'message': None, 'data': , 'otherData'
[解绑账号]data解码:
解绑成功

**Comment by ChrisKimZHT** [comment]
> [获取SessionlD]返回消息:
> 
> 'status ': True, 'code': o, 'message': None, 'data':
> 
> '' , 'otherData': 0}
> 
> [获取SessionlD] data解码:
> 
> {'bind": False, 'sessionld': ''}[绑定身份]返回消息:
> 
> {'status': False, 'code': 50000, 'message':'身份证信息错误', 'data': None, "otherData': {}
> 
> [解绑账号]返回消息:
> 
> {'status': True,'code': o, 'message': None, 'data': , 'otherData'
> 
> [解绑账号]data解码:
> 
> 解绑成功
> 
> 

是否确定账号与密码正确？如果确定正确可早晨再进行运行尝试，晚上学校服务器有时候会出问题。

我是每天7:40运行，到昨天为止还未出现问题。

**Comment by sssolitude** [comment]
> > [获取SessionlD]返回消息:
> > 'status ': True, 'code': o, 'message': None, 'data':
> > '' , 'otherData': 0}
> > [获取SessionlD] data解码:
> > {'bind": False, 'sessionld': ''}[绑定身份]返回消息:
> > {'status': False, 'code': 50000, 'message':'身份证信息错误', 'data': None, "otherData': {}
> > [解绑账号]返回消息:
> > {'status': True,'code': o, 'message': None, 'data': , 'otherData'
> > [解绑账号]data解码:
> > 解绑成功
> 
> 是否确定账号与密码正确？如果确定正确可早晨再进行运行尝试，晚上学校服务器有时候会出问题。
> 
> 我是每天7:40运行，到昨天为止还未出现问题。

  账号密码确定是正确的，但是我是20级在系统里的账号是身份证号，且身份证号里带有X，这个会影响吗，我今天又尝试了还是一样的问题。
![1653962670](https://user-images.githubusercontent.com/62141843/171078486-49a38498-c81f-49e5-90df-e914d54b70be.jpg)

**Comment by ChrisKimZHT** [comment]
>   账号密码确定是正确的，但是我是20级在系统里的账号是身份证号，且身份证号里带有X，这个会影响吗，我今天又尝试了还是一样的问题。
> 
> ![1653962670](https://user-images.githubusercontent.com/62141843/171078486-49a38498-c81f-49e5-90df-e914d54b70be.jpg)
> 
> 

请问你们填报系统不一样吗，在小程序内登录也是使用身份证号作为账号的嘛？

可以先尝试解绑微信小程序，再输入你的账号密码在小程序登录。如果小程序可以正常登录那这个程序也应该可以登录。

**Comment by sssolitude** [comment]
> > 账号密码确定是正确的，但是我是20级在系统里的账号是身份证号，且身份证号里带有X，这个会影响吗，我今天又尝试了还是一样的问题。
> > ![1653962670](https://user-images.githubusercontent.com/62141843/171078486-49a38498-c81f-49e5-90df-e914d54b70be.jpg)
> 
> 请问你们填报系统不一样吗，在小程序内登录也是使用身份证号作为账号的嘛？
> 
> 可以先尝试解绑微信小程序，再输入你的账号密码在小程序登录。如果小程序可以正常登录那这个程序也应该可以登录。

哦研究生的系统不一样，我的锅

**Comment by ChrisKimZHT** [comment]
嗯，请问方便提供下你们的系统地址嘛，我可以尝试添加研究生的功能。（不过没账号，可能做不出来）

**Comment by sssolitude** [comment]
> 嗯，请问方便提供下你们的系统地址嘛，我可以尝试添加研究生的功能。（不过没账号，可能做不出来）

我改出来啦，谢谢大佬orz

**Comment by sssolitude** [comment]
https://yjsxx.whut.edu.cn/wx

**Comment by ChrisKimZHT** [comment]
> > 嗯，请问方便提供下你们的系统地址嘛，我可以尝试添加研究生的功能。（不过没账号，可能做不出来）
> 
> 
> 
> 我改出来啦，谢谢大佬orz

嚯，这么快，不如推个Pull Request吧
