### ISSUE TITLE
用win10无法自动运行打包后的程序

### ISSUE THREAD

**Issue by yanfan98** [ChrisKimZHT/WHUT-AutoHealthReport#3]
用win10对打包后的程序进行自动运行，每次运行程序都提示未发现配置文件，进行配置文件初始化
双击打开倒是没问题，源码可以自动运行

**Comment by yanfan98** [comment]
我把那个配置文件放到system32里面就好了

**Comment by ChrisKimZHT** [comment]
> 用win10对打包后的程序进行自动运行，每次运行程序都提示未发现配置文件，进行配置文件初始化
> 
> 双击打开倒是没问题，源码可以自动运行

程序使用的相对目录，因此会在你命令行的当前目录查找配置文件。命令行默认目录是system32。

因此用批处理自动运行时请先cd到程序目录再运行，而不是直接用绝对目录启动程序。
