### ISSUE TITLE
能否搞个安卓版的？

### ISSUE THREAD

**Issue by An-gao** [ChrisKimZHT/WHUT-AutoHealthReport#4]
晚上11点会断电，校园网会时不时需要重新登录，部署在上服务器我不会。可以请喝奶茶。

**Comment by ChrisKimZHT** [comment]
感谢提议，之后有可能会研究下 Python 安卓应用。不过我的印象中手机似乎也没有定时运行某程序的功能吧，如果你的意思是手动点开运行，那岂不是和打开微信小程序打卡差不多了。

如果不会部署在服务器，可以尝试云函数，这个更加轻量和简单。当然，这些服务往往是要花钱的，也得你自己学习下如何使用。

**Comment by An-gao** [comment]
现在手机都有自动任务，可以设置定时打开某个软件

**Comment by ChrisKimZHT** [comment]
> 现在手机都有自动任务，可以设置定时打开某个软件

好的，那就挺方便。
