### ISSUE TITLE
日志

### ISSUE THREAD

**Issue by Zhang-CH0** [ChrisKimZHT/WHUT-AutoHealthReport#5]
日志中出现其他人的账号信息，我觉得这个可能存在信息泄露，昨天看日志，看到别人的日志

**Comment by ChrisKimZHT** [comment]
我也遇到过，这个是学校系统的神奇 bug 哈，不用担心。

这个 bug 触发条件似乎是时间？我不太清楚，我很久以前在 6:30 左右打卡串号了好几次，现在一直 7:40 打卡没有遇到过该 bug。

**Comment by Zhang-CH0** [comment]
我设置的是11点，昨天有这个问题，今天就没有，昨天日志中第一遍是打卡失败别人的信息，第二遍才是我的，今天就没有了


&nbsp;


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haotian ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ChrisKimZHT/WHUT-AutoHealthReport] 日志 (Issue #5)





 
我也遇到过，这个是学校系统的神奇 bug 哈，不用担心。
 
这个 bug 触发条件似乎是时间？我不太清楚，我很久以前在 6:30 左右打卡串号了好几次，现在一直 7:40 打卡没有遇到过该 bug。

**Comment by Zhang-CH0** [comment]
我的建议是不显示这部分信息，只反馈打卡是否成功
&nbsp;


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haotian ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ChrisKimZHT/WHUT-AutoHealthReport] 日志 (Issue #5)





 
我也遇到过，这个是学校系统的神奇 bug 哈，不用担心。
 
这个 bug 触发条件似乎是时间？我不太清楚，我很久以前在 6:30 左右打卡串号了好几次，现在一直 7:40 打卡没有遇到过该 bug。

**Comment by Zhang-CH0** [comment]
我想可以加一个验证信息，例如用姓名验证，假设不是对应姓名的就不打印对应的日志，这样就可以假装没有那个bug
&nbsp;


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haotian ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ChrisKimZHT/WHUT-AutoHealthReport] 日志 (Issue #5)





 
我也遇到过，这个是学校系统的神奇 bug 哈，不用担心。
 
这个 bug 触发条件似乎是时间？我不太清楚，我很久以前在 6:30 左右打卡串号了好几次，现在一直 7:40 打卡没有遇到过该 bug。

**Comment by ChrisKimZHT** [comment]
日志也只有你一个人能看到哈，每次运行都会覆盖上一次的日志，所以只要你保管好是没有信息泄露的问题的。

（要说信息泄露也得怪学校

**Comment by ChrisKimZHT** [comment]
另外，日志就是为了调试问题，没必要判断是否是正确姓名。如果我不打印这些信息，之后出问题后我都找不到 bug 在哪。

**Comment by ChrisKimZHT** [comment]
`v1.2.2` 版已经解决了账号不匹配问题，若绑定身份时发现帐号不匹配，程序会终止，然后进行三次重试。
